### ISSUE TITLE
Пример конфига

### ISSUE THREAD

**Issue by didjeru** [KomX/ESPHome-Ready4Sky#1]
```
esphome:
  name: skykettle

esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: latest

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_pass
  fast_connect: true
  ap:
    ssid: esp32
    password: !secret esp_pass
  
ota:
  password: !secret esp_api
api:
  password: !secret esp_api

logger:
  level: INFO
  baud_rate: 0

substitutions:
  kettle: RK-G203S

external_components:
  - source: github://KomX/ESPHome-Ready4Sky/components
time:
  - platform: homeassistant
  
ready4sky:
  scan_parameters:
    interval: 150 ms
    window: 50 ms
    duration: 30 s

skykettle:
  - mac_address: XX:XX:XX:XX:XX:XX
    model: RK-G203S
    cup_volume: 250
    cup_correction: 1.534286
    informing:
      energy:
        name: ${kettle} Energy
      temperature:
        name: ${kettle} Temperature
      cup_quantity:
        name: ${kettle} Cup(s)
      water_volume:
        name: ${kettle} Water Volume
      signal_strength:
        name: ${kettle} RSSI
      work_cycles:
        name: ${kettle} Work Cycles
      work_time:
        name: ${kettle} Work Time
      status_indicator:
        name: ${kettle} Status
    controlling:
      power:
        name: ${kettle} Power
      target_temperature:
        name: ${kettle} Target
      boil_time_adjustment:
        name: ${kettle} Boil Adj
      state_led:
        name: ${kettle} State Led
      background_light:
        name: ${kettle} Night Light
      beeper:
        name: ${kettle} Beeper
```
